package chazzwsg;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Chazz
 */
public class WeatherShowSetLocation extends javax.swing.JDialog {

	private WeatherShowView wsv;
	private String locationText = "Type name of your location";
	private DefaultListModel listModel = new DefaultListModel();
	private SearchLocation search;

	public WeatherShowSetLocation(javax.swing.JFrame parent) {
		super(parent, true);
		initComponents();
		wsv = (WeatherShowView) parent;
	}

	public void showError(String err) {
		JOptionPane.showMessageDialog(rootPane, err, "Error", 0);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultList = new javax.swing.JList();
        setLocationButton = new javax.swing.JButton();
        locationField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set your location");
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        setResizable(false);

        progressBar.setFocusable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Set your location"));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        resultList.setModel(listModel);
        resultList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        resultList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultListMouseClicked(evt);
            }
        });
        resultList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                resultListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(resultList);

        setLocationButton.setText("Set location");
        setLocationButton.setEnabled(false);
        setLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLocationButtonActionPerformed(evt);
            }
        });

        locationField.setToolTipText("Type the name of your locaiton");
        locationField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                locationFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                locationFieldFocusLost(evt);
            }
        });
        locationField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                locationFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(locationField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton))
                    .addComponent(setLocationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(locationField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setLocationButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
		search = new SearchLocation(this);
		Runnable newTask = new Runnable() {

			@Override
			public void run() {
				String query = locationField.getText().trim().replace(" ", "+");

				progressBar.setIndeterminate(true);
				search.setQuery(query);
				String[] results = search.getResults();

				listModel.clear();
				if ((results != null) && (results.length > 0)) {
					for (int i = 0; i < results.length; i++) {
						listModel.insertElementAt(results[i], i);
					}
				} 
				progressBar.setIndeterminate(false);
			}
		};
		new Thread(newTask).start();


	}//GEN-LAST:event_searchButtonActionPerformed

	private void resultListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_resultListValueChanged
		setLocationButton.setEnabled(true);
	}//GEN-LAST:event_resultListValueChanged

	private void locationFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationFieldFocusGained
		if (locationField.getText().equals(locationText)) {
			locationField.setText(null);
		}
	}//GEN-LAST:event_locationFieldFocusGained

	private void locationFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationFieldFocusLost
		if (locationField.getText().equals("")) {
			locationField.setText(locationText);
		}
	}//GEN-LAST:event_locationFieldFocusLost

	private void locationFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_locationFieldKeyPressed
		evt.getKeyChar();
		if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
			searchButtonActionPerformed(null);
		}
	}//GEN-LAST:event_locationFieldKeyPressed

	private void setLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLocationButtonActionPerformed
		try {
			wsv.setWeatherLocation(resultList.getSelectedValue().toString());

			this.setVisible(false);
		} catch (NullPointerException ex) {
			System.out.println("nema select");
		}
	}//GEN-LAST:event_setLocationButtonActionPerformed

	private void resultListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultListMouseClicked
		if (evt.getClickCount() == 2 && !evt.isConsumed()) {
			evt.consume();
			setLocationButtonActionPerformed(null);
		}
	}//GEN-LAST:event_resultListMouseClicked

	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField locationField;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JList resultList;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton setLocationButton;
    // End of variables declaration//GEN-END:variables
}
